### PR TITLE
Add SHAP Decision Plots to Summary Plots

### LINKED ISSUE #287: add SHAP decision plot to results page
add a decision plot for visualizing individual sample predictions broken down by feature.

### PR DESCRIPTION
**Pull request by nupurbaghel**
Both summary and decision plot features are sorted by feature importance.

Fixes #287

### CODE REVIEW

**Comment by nupurbaghel** [comment]
Sample result generated -

Screen Shot 2020-11-04 at 2 04 34 PM

**Comment by lacava** [comment]
- [ ] update help text
- [ ] update title (e.g. "SHAP analysis")
- [ ] add LinearExplainer

**Comment by nupurbaghel** [comment]
TODOs
- [ ] PMLB large dataset testing
- [ ] SHAP Analysis (change header)
- [ ] Update description
- [ ] Add Linear explainer - Linear Regression, Logistic Regression
- [ ] Convert class name to lower case

**Comment by nupurbaghel** [comment]
I tested using the Kddcup dataset in PMLB suggested:  https://github.com/EpistasisLab/pmlb/tree/master/datasets/kddcup
- Since this was exceeding PennAI's max file size, I sub-sampled to get approximately 58791 rows (0.119%) of the data-set.
- Tried using Logistic Regression and Decision Tree models. Both of them timed out, hence decided to sample 100 rows for the case of Linear and Tree Explainers.

**Review by lacava — CHANGES_REQUESTED** [review]
Everything looks good! Please update the info text a bit. Otherwise I think it's ready to merge.

**Review by lacava — APPROVED** [review]

**Review by hjwilli — APPROVED** [review]
Great job!  Good to merge.

**Pull request merged**
