### PR TITLE
SHAP Summary Plot

### PR DESCRIPTION
**Pull request by nupurbaghel**
Adding implementation to visualize SHAP Summary plots for Classification models

- Currently plot images for all classes are created and stored.
- Kernel based explainers are slow, so random sampling of 50 features is performed (updated as 200 was working slower on the recent branch with regression)
- Summary Curves with multiple classes are displayed using a modified form of InvertedCard, named InvertedCardWithDropdown

### CODE REVIEW

**Comment by nupurbaghel** [comment]
Further, we can additionally have -
- [ ] SHAP plot "not available" message inside a Card
- [ ] Tooltip Information 
- [ ] Limit on the number of features to select (10 or 20?)

**Comment by nupurbaghel** [comment]
@hjwilli There seems to be this error  `No module named 'shap'` 
I have added shap to the requirements file so not sure why its still present.

**Comment by weixuanfu** [comment]
@nupurbaghel please also add `shap==0.34.0` into [requirements for unit tests](https://github.com/EpistasisLab/pennai/blob/master/tests/unit/files/requirements.txt)

**Comment by nupurbaghel** [comment]
Added unit tests to check that Summary Plots are:
1.  Not generated for SVC, Linear SVC algorithms
2. In case of binary classification, Gradient Boosting generates only one plot (Tree Explainer exception)
3. For all other classification tests, number of plots equals the number of output classes.

**Comment by hjwilli** [comment]
SHAP summary plot now reports the kernel and number of samples (if less then max) used to generate the plot.

shap_help

shap_help2

**Pull request merged**
