### PR TITLE
 Sklearn-API of PennAI AI engine

### PR DESCRIPTION
**Pull request by weixuanfu**
Related issue #253 #265

- Add scikit-learn wrapper for PennAI AI engine in `ai/pennai_sklearn.py`
- Unit tests for the scikit-learn wrapper is `ai/tests/test_sklearn_api.py`
- Add docs in `docs/guides/userGuide.md` for installation and a small example
- Edit `setup.py` for installation in `pip` after release (pyp repo is not available yet)

### CODE REVIEW

**Comment by weixuanfu** [comment]
- [ ] disable save function for now
- [ ] provide pre-trained SVD recommender
- [ ] Add docs for how to use pre-trained SVD recommender

**Comment by weixuanfu** [comment]
Check this [pre-release on pypi](https://pypi.org/project/pennaipy/0.17a0)

**Review by lacava — CHANGES_REQUESTED** [review]
- [ ] Suggest to rename the module to pennai (right now it's called "ai")

- [ ] docs: they look good! but is there a way to specify the dependencies in setup.py or in an environment file?

- [ ] when installing from scratch I get the error "ModuleNotFoundError: No module named 'simplejson'" when I run the example. So simplejson needs to be added to dependencies.

**Comment by lacava** [comment]
when installing the pip package and running the example, i get the error: 

> FileNotFoundError: [Errno 2] No such file or directory: 'data/knowledgebases/sklearn-benchmark-data-knowledgebase-r6-small.tsv.gz'

i don't see these files in the pypi package that is installed. You might need to add package data to setup.py like [we do here](https://github.com/EpistasisLab/penn-ml-benchmarks/blob/d11384d7786e642bcd0f5c16a5885b2624873c0c/setup.py#L20)
full output:

> FileNotFoundError                         Traceback (most recent call last)
<ipython-input-1-664bdac93a8b> in <module>
     22               )
     23 
---> 24 pennai.fit(X_train, y_train)
     25 print(pennai.score(X_test, y_test))
>
> ~/anaconda3/lib/python3.8/site-packages/ai/sklearn/pennai_sklearn.py in fit(self, X, y)
>     437         """
>     438 
> --> 439         self.fit_init_()
>     440 
>     441 
> 
> ~/anaconda3/lib/python3.8/site-packages/ai/sklearn/pennai_sklearn.py in fit_init_(self)
>     148 
>     149 
> --> 150         self.initilize_recommenders(self.rec_class)  # set self.rec_engine
>     151 
>     152 
> 
> ~/anaconda3/lib/python3.8/site-packages/ai/sklearn/pennai_sklearn.py in initilize_recommenders(self, rec_class)
>     285 
>     286         if self.knowledgebase and self.kb_metafeatures:
> --> 287             resultsData = self.load_kb()
>     288             logger.info('Knowledgebase loaded')
>     289         else:
> 
> ~/anaconda3/lib/python3.8/site-packages/ai/sklearn/pennai_sklearn.py in load_kb(self)
>     318         logger.info('loading pmlb knowledgebase')
>     319 
> --> 320         kb = load_knowledgebase(
>     321             resultsFiles=[self.knowledgebase],
>     322             metafeaturesFiles=[self.kb_metafeatures]
> 
> ~/anaconda3/lib/python3.8/site-packages/ai/knowledgebase_utils.py in load_knowledgebase(resultsFiles, metafeaturesFiles, jsonMetafeatureDirectory, dedupe)
>      85     frames = []
>      86     for resultsFile in resultsFiles:
> ---> 87         frames.append(_load_results_from_file(resultsFile))
>      88 
>      89     logger.info("concatenating results....")
> 
> ~/anaconda3/lib/python3.8/site-packages/ai/knowledgebase_utils.py in _load_results_from_file(resultsFile)
>     319     # resultsfile is a tsv file
>     320     if resultsFile.endswith('tsv.gz') or resultsFile.endswith('tsv'):
> --> 321         results_data = pd.read_csv(resultsFile, sep='\t')
>     322 
>     323         # convert params to dictionary
> 
> ~/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py in read_csv(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)
>     684     )
>     685 
> --> 686     return _read(filepath_or_buffer, kwds)
>     687 
>     688 
> 
> ~/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py in _read(filepath_or_buffer, kwds)
>     450 
>     451     # Create the parser.
> --> 452     parser = TextFileReader(fp_or_buf, **kwds)
>     453 
>     454     if chunksize or iterator:
> 
> ~/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py in __init__(self, f, engine, **kwds)
>     934             self.options["has_index_names"] = kwds["has_index_names"]
>     935 
> --> 936         self._make_engine(self.engine)
>     937 
>     938     def close(self):
> 
> ~/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py in _make_engine(self, engine)
>    1166     def _make_engine(self, engine="c"):
>    1167         if engine == "c":
> -> 1168             self._engine = CParserWrapper(self.f, **self.options)
>    1169         else:
>    1170             if engine == "python":
> 
> ~/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py in __init__(self, src, **kwds)
>    1996         kwds["usecols"] = self.usecols
>    1997 
> -> 1998         self._reader = parsers.TextReader(src, **kwds)
>    1999         self.unnamed_cols = self._reader.unnamed_cols
>    2000 
> 
> pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader.__cinit__()
> 
> pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._setup_parser_source()
> 
> ~/anaconda3/lib/python3.8/gzip.py in __init__(self, filename, mode, compresslevel, fileobj, mtime)
>     171             mode += 'b'
>     172         if fileobj is None:
> --> 173             fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
>     174         if filename is None:
>     175             filename = getattr(fileobj, 'name', '')
> 
> FileNotFoundError: [Errno 2] No such file or directory: 'data/knowledgebases/sklearn-benchmark-data-knowledgebase-r6-small.tsv.gz'

**Comment by weixuanfu** [comment]
@lacava  Thank you for the feedback. I just updated docs for testing the pip-installed package. https://github.com/EpistasisLab/pennai/pull/273/commits/b209189d3f99b4a5782f0d9a4e4b0699a3a716f5

But I did not agree that we should put knowledgebase/metefeatures/pickled recommenders into the pypi package because it will make the package oversize. Let's discuss about it in our meeting soon.

**Comment by weixuanfu** [comment]
- [New docs markdown](https://github.com/EpistasisLab/pennai/blob/ai_sklearn_api/docs/guides/Scikit_Learn_API_Guide.md)
- [Per-release Pypi packge](https://pypi.org/project/pennaipy/0.17a1/) `pip install pennaipy==0.17a1`

**Comment by weixuanfu** [comment]
>     * docs: they look good! but is there a way to specify the dependencies in setup.py or in an environment file?

I added most of dependencies into setup.py. But we still need this installation docs because the surprise package cannot installed normally but from a forked GitHub repo.

**Comment by hjwilli** [comment]
A few suggestions for the docs:

- the anaconda dl link didn't work, looks like it may have moved to https://www.anaconda.com/products/individual
- perhaps add a section that describes in a more detail how to use the PennAIClassifier/PennAIRegressor classes or add a link to the api docs for those classes so users can see the parameter options
- At least for windows, Microsoft Visual C++ 14.0 seems to be a requirement to build the surprise package.  Perhaps list as a prereq for that step in the docs.  When running `pip install --no-cache-dir git+https://github.com/lacava/surprise.git@1.0.8.3` initially, I got the following:
```
copying surprise\prediction_algorithms\slope_one.pyx -> build\lib.win-amd64-3.7\surprise\prediction_algorithms
running build_ext
building 'surprise.similarities' extension
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
```

**Comment by hjwilli** [comment]
Travis encrypted credentials documentation:
https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings

**Comment by weixuanfu** [comment]
> Travis encrypted credentials documentation:
> https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings

Thank you for finding out this setting. I just made a commit 6c93a1e7d50d39d88894b2ebcc1d7c6968efeebb for using deployment in travis instead of GitHub Action. I never use this way before but it is worth to try.

**Comment by hjwilli** [comment]
Hi @weixuan, thanks for helping troubleshoot and for updating the documentation, I was able to install and run the test scripts.  A few small documentation/code cleanup tasks:

- in pennai_scikitlearn.py, make sure all non-public methods in the `PennAI` class start with "_" as per pep8
- add the `PennAI` class to the API documentation, and make sure all public methods for the `PennAI` class appear in the docs
- if possible, note in the scikit learn userguide that detailed usage info can be found in the API docs, and link to the relevant section

**Review by hjwilli — APPROVED** [review]
This looks great!

**Pull request merged**
