### PR TITLE
webapp - update react from 15.6.2 to 16.13.1

### PR DESCRIPTION
**Pull request by mgstauffer**
Update all dependencies.
Fix new warning in ExperimentsTableHeader, caused by use of boolean and
number in conditional for setting rowSpan and colSpan.
NOTE - one npm warning remains about react-native but seems ok to ignore (try 'npm ls')

### CODE REVIEW

**Comment by mgstauffer** [comment]
@hjwilli Here's a branch that does just the upgrade to React 16.13.1. It seems to have gone really well and wasn't much trouble, just chasing down little details. The tests pass. I've played around with the build and it seems to work as expected (upload new data, run ai, view experiments), but I have little experience so could you try the site and see what you think?

**Comment by hjwilli** [comment]
I noticed one small UI bug, on the `/experiments` page, the 'Actions' header is not aligned with the drop down columns.  All the site functionality seemed to work, I didn't notice any other issues.

datasets

**Comment by mgstauffer** [comment]
OK I'll see if I can fix the ui alignment bug

**Comment by mgstauffer** [comment]
I've fixed the UI alignment bug

**Pull request merged**
