### PR TITLE
Dataset upload ui updates

### PR DESCRIPTION
**Pull request by mgstauffer**
Hmm, I thought I made a pull request for this last week.
In any case, I ran various manual functionality tests again, and made some cosmetic changes, including adding row numbers.

### CODE REVIEW

**Review by weixuanfu — CHANGES_REQUESTED** [review]
1. on the ordinal/categorical feature inputs, the texts are too close to left side of the pop-up windows. I think need 2-4 blank spaces in each line.  
Screen Shot 2020-11-19 at 1 35 30 PM
Screen Shot 2020-11-19 at 1 35 52 PM

2. Suggestion: Using "Set Ordinal" and "Set Categorical" on the bottons on the screenshot below. 

Screen Shot 2020-11-19 at 1 36 42 PM

3. Please rebase the branch to master branch for passing CI builds.

**Comment by mgstauffer** [comment]
I've addressed @weixuanfu items 1 & 2 from https://github.com/EpistasisLab/pennai/pull/298#pullrequestreview-534745506
But origin/master doesn't have a new commit (current is from Nov 6). Is there a branch with the CI fixes waiting to be merged into master?

**Comment by weixuanfu** [comment]
Hmm, I am not sure why CI builds failed. I will check it tomorrow.

> I've addressed @weixuanfu items 1 & 2 from [#298 (review)](https://github.com/EpistasisLab/pennai/pull/298#pullrequestreview-534745506)
> But origin/master doesn't have a new commit (current is from Nov 6). Is there a branch with the CI fixes waiting to be merged into master?

**Comment by weixuanfu** [comment]
Hmm Could you please fix [those failed tests for uploading dataset](https://travis-ci.org/github/EpistasisLab/pennai/jobs/744771168#L5767-L5774) in CI builds?

**Pull request merged**
